/* DO NOT EDIT THIS FILE!  It is auto-generated from a list of values in ./rsync.1.md! */

#define DEFAULT_CVSIGNORE "RCS SCCS CVS CVS.adm RCSLOG cvslog.* tags TAGS .make.state .nse_depinfo *~ #* .#* ,* _$* *$ *.old *.bak *.BAK *.orig *.rej .del-* *.a *.olb *.o *.obj *.so *.exe *.Z *.elc *.ln core .svn/ .git/ .hg/ .bzr/"
